# frozen_string_literal: true

module Api::V1::ReleaseEngines
  # Squirrel.Windows RELEASES endpoint. Redirects to the RELEASES artifact
  # uploaded by the user for the latest available upgrade. The RELEASES
  # file is a build artifact generated by electron-builder or Squirrel
  # that contains the nupkg manifest.
  #
  # See: https://github.com/electron/update.electronjs.org
  class Electron::ReleasesController < Api::V1::BaseController
    before_action :scope_to_current_account!
    before_action :require_active_subscription!
    before_action :authenticate_with_token
    before_action :set_package, only: %i[show]

    typed_query {
      param :constraint, type: :string, optional: true
      param :channel, type: :string, optional: true
    }
    def show
      authorize! package

      platform = params[:platform]
      arch     = params[:arch]

      releases = authorized_scope(package.releases)
      release  = releases.find_by!(version: params[:version])
      authorize! release, to: :upgrade?

      kwargs  = release_query.slice(:constraint, :channel)
      upgrade = release.upgrade!(**kwargs)
      authorize! upgrade

      artifacts = authorized_scope(upgrade.artifacts)
      artifact  = artifacts.joins(:platform, :arch)
                           .where(
                             release_artifacts: { filename: 'RELEASES' },
                             platform: { key: platform },
                             arch: { key: arch },
                           )
                           .reorder(created_at: :desc)
                           .first!
      authorize! artifact

      BroadcastEventService.call(
        event: 'release.upgraded',
        account: current_account,
        resource: upgrade,
        meta: {
          current: release.version,
          next: upgrade.version,
        },
      )

      redirect_to vanity_v1_account_release_artifact_url(artifact.account, artifact, filename: artifact.filename, host: request.host),
        status: :see_other,
        allow_other_host: true
    rescue ActiveRecord::RecordNotFound
      render_no_content
    end

    private

    attr_reader :package

    def set_package
      @package = Current.resource = FindByAliasService.call(
        authorized_scope(current_account.release_packages.electron),
        id: params[:package],
        aliases: :key,
      )
    end
  end
end
