# frozen_string_literal: true

# TODO(ezekg) eventually refactor validation service into models
class LicenseValidation
  CODES = %w[
    BANNED
    CHECKSUM_SCOPE_MISMATCH
    CHECKSUM_SCOPE_REQUIRED
    COMPONENTS_SCOPE_EMPTY
    COMPONENTS_SCOPE_MISMATCH
    COMPONENTS_SCOPE_REQUIRED
    ENTITLEMENTS_MISSING
    ENTITLEMENTS_SCOPE_EMPTY
    ENVIRONMENT_SCOPE_MISMATCH
    ENVIRONMENT_SCOPE_REQUIRED
    EXPIRED
    FINGERPRINT_SCOPE_EMPTY
    FINGERPRINT_SCOPE_MISMATCH
    FINGERPRINT_SCOPE_REQUIRED
    HEARTBEAT_DEAD
    HEARTBEAT_NOT_STARTED
    MACHINE_SCOPE_MISMATCH
    MACHINE_SCOPE_REQUIRED
    NO_MACHINE
    NO_MACHINES
    NOT_FOUND
    OVERDUE
    POLICY_SCOPE_MISMATCH
    POLICY_SCOPE_REQUIRED
    PRODUCT_SCOPE_MISMATCH
    PRODUCT_SCOPE_REQUIRED
    SUSPENDED
    TOO_MANY_CORES
    TOO_MANY_MACHINES
    TOO_MANY_PROCESSES
    TOO_MANY_USERS
    TOO_MUCH_DISK
    TOO_MUCH_MEMORY
    USER_SCOPE_MISMATCH
    USER_SCOPE_REQUIRED
    VALID
    VERSION_SCOPE_MISMATCH
    VERSION_SCOPE_REQUIRED
  ].freeze
end
